#!/usr/bin/env node
// Re-render cover-letter.md + cover-letter.pdf for an existing staged role,
// pulling new plain-text body from a file. Used when a cover letter is
// hand-written instead of generated by stage-applications.mjs.
//
// usage: node rerender-cover.mjs <slug> <plain-text-file>

import { readFile, writeFile, mkdir, copyFile, stat } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { chromium } from 'playwright';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const slug = process.argv[2];
const inputPath = process.argv[3];
const companyArg = process.argv[4];
const roleArg = process.argv[5];
const urlArg = process.argv[6];
const scoreArg = process.argv[7];
const daysArg = process.argv[8];

if (!slug || !inputPath) {
  console.error('usage: rerender-cover.mjs <slug> <plain-text-file> [company] [role] [url] [score] [daysOld]');
  console.error('  if no existing output/<slug>/cover-letter.md, last 5 args are required to create from scratch');
  process.exit(2);
}

const dir = path.join(ROOT, 'output', slug);
await mkdir(dir, { recursive: true });

const profile = await readFile(path.join(ROOT, 'config/profile.yml'), 'utf-8').catch(() => '');
const newText = (await readFile(inputPath, 'utf-8')).trim();

let company = companyArg || '';
let role = roleArg || '';
let url = urlArg || '';
let score = scoreArg || '';
let days = daysArg || '';

const mdPath = path.join(dir, 'cover-letter.md');
let preserveHeader = '';
try {
  const oldMd = await readFile(mdPath, 'utf-8');
  // Pull the metadata block + heading
  const headingLine = oldMd.match(/^# Cover letter.*$/m);
  const heading = headingLine ? headingLine[0] : '';
  const m = heading.match(/^# Cover letter\s*[—\-]\s*(.+?):\s*(.+)$/);
  if (!company && m) company = m[1];
  if (!role && m) role = m[2];
  const urlM = oldMd.match(/\*\*URL:\*\*\s+(\S+)/);
  if (!url && urlM) url = urlM[1];
  const scoreM = oldMd.match(/\*\*Score:\*\*\s+(\S+)/);
  if (!score && scoreM) score = scoreM[1];
  const daysM = oldMd.match(/\*\*Days old at staging:\*\*\s+(\S+)/);
  if (!days && daysM) days = daysM[1];
  preserveHeader = `# Cover letter - ${company}: ${role}\n\n**URL:** ${url}\n**Generated:** ${new Date().toISOString()}\n**Days old at staging:** ${days}\n**Score:** ${score}\n\n---\n`;
} catch {
  // No existing md - build from scratch
  if (!company || !role || !url) {
    console.error('No existing cover-letter.md and required metadata args missing');
    process.exit(2);
  }
  preserveHeader = `# Cover letter - ${company}: ${role}\n\n**URL:** ${url}\n**Generated:** ${new Date().toISOString()}\n**Days old at staging:** ${days || 'n/a'}\n**Score:** ${score || 'n/a'}\n\n---\n`;
}

await writeFile(mdPath, preserveHeader + '\n' + newText + '\n');

// Copy shared cv.pdf into the role dir if present
const sharedCv = path.join(ROOT, 'output', 'cv.pdf');
try {
  await stat(sharedCv);
  await copyFile(sharedCv, path.join(dir, 'cv.pdf'));
} catch {}

// Render the cover letter PDF
const candName = (profile.match(/full_name:\s*"([^"]+)"/) || [])[1] || 'Vitor Pontual';
const email = (profile.match(/email:\s*"([^"]+)"/) || [])[1] || '';
const phone = (profile.match(/phone:\s*"([^"]+)"/) || [])[1] || '';
const linkedin = (profile.match(/linkedin:\s*"([^"]+)"/) || [])[1] || '';
const today = new Date().toISOString().slice(0, 10);

const escaped = newText.split('\n').map(l => l.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')).join('<br>\n');
const html = `<!doctype html><html><head><meta charset="utf-8"><style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.55; color: #111; padding: 0; }
  .head { border-bottom: 1px solid #ccc; padding-bottom: 0.15in; margin-bottom: 0.25in; }
  .name { font-size: 18pt; font-weight: 600; letter-spacing: -0.01em; }
  .contact { font-size: 9.5pt; color: #555; margin-top: 4px; }
  .meta { font-size: 9pt; color: #666; margin: 0.25in 0; }
  .body { margin: 0.1in 0; }
</style></head><body>
  <div class="head">
    <div class="name">${candName}</div>
    <div class="contact">${[email, phone, linkedin].filter(Boolean).join(' · ')}</div>
  </div>
  <div class="meta">${today}<br>Re: ${role}, ${company}</div>
  <div class="body">${escaped}</div>
</body></html>`;

const browser = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await browser.newContext();
const page = await ctx.newPage();
await page.setContent(html);
await page.emulateMedia({ media: 'print' });
await page.pdf({
  path: path.join(dir, 'cover-letter.pdf'),
  format: 'Letter',
  margin: { top: '0.7in', bottom: '0.7in', left: '0.85in', right: '0.85in' }
});
await browser.close();
console.log(`OK ${slug}: re-rendered cover-letter.md + cover-letter.pdf`);
